### ISSUE TITLE
explore data sets

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/team-assignment-team1#2]
To do:
- download data for one city (all types of datasets)
- try to load them into R

__Deliverable:__
- describe to your team members (here) what you can get in each of the datasets
- also address time availability

**Comment by MatthijsvanGils** [comment]
Deliverable 

1.  loaded the data files of Amsterdam using the code of @KleinJonasUVT 
url <- "http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2022-12-05/data/listings.csv.gz"
download.file(url, destfile = "listings.csv.gz")



2. Summary of the data 

**listings.csv.gz** - This file contains detailed information on each Airbnb listing in Amsterdam, including the listing ID, the host ID, the name of the listing, the listing type (e.g. entire home, private room, shared room), the number of guests the listing can accommodate, the neighborhood where the listing is located, the price per night, and many other details.

**calendar.csv.gz** - This file provides information on the availability and price of each Airbnb listing in Amsterdam for each day of the year. It includes the listing ID, the date, the availability (i.e. whether the listing is available to be booked on that date), and the price of the listing on that date.

**reviews.csv.gz** - This file contains reviews of Airbnb listings in Amsterdam. It includes the listing ID, the reviewer ID, the date of the review, the text of the review, and other details.

**neighbourhoods.csv** - This file provides information on the neighborhoods in Amsterdam, including their names and geographic boundaries.

neighbourhoods.geojson - This file contains the same information as neighbourhoods.csv, but in the form of a GeoJSON file, which can be used to create maps and other visualizations.

Overall, these data files provide a wealth of information about Airbnb listings in Amsterdam, including details on each listing, its availability and price, reviews from past guests, and information about the city's neighborhoods.


3. Time availability
We tackled this part during the first online meeting in class. For historical data, we searched github for data sets from previous years. We have found these and therefore it is possible to compare data from 2020 and 2022
