### ISSUE TITLE
Search for papers on cities most affected by covid

### ISSUE THREAD

**Issue by marijnbransen1998** [course-dprep/team-assignment-team1#5]
to do:

- find papers that mention which cities where most affected by covid-19
- Look if these cities have data on airbnb

Deliverable:

- Show the other team-members which cities you found and if they are available to research

**Comment by hannesdatta** [comment]
- please also extend to blogs talking about how different cities handling the lockdowns.

**Comment by marijnbransen1998** [comment]
Not relevant anymore since we changed the research question!
